# Generated by Django 5.2.7 on 2025-10-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('address', models.CharField(max_length=255)),
                ('job_history', models.TextField(help_text='List or description of previous jobs')),
                ('education_history', models.TextField(help_text='List or description of education')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
