# Generated by Django 5.2.7 on 2025-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_history',
            field=models.TextField(help_text='List of schools, universities, or certifications'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_history',
            field=models.TextField(help_text='List of previous jobs or experiences'),
        ),
    ]
